export const ACTION_GET_ADVERTISEMENTS = 'ACTION_GET_ADVERTISEMENTS';
export const ACTION_CREATE_ADVERTISEMENT = 'ACTION_CREATE_ADVERTISEMENT';
export const ACTION_GET_ADVERTISEMENT_BY_ID = 'ACTION_GET_ADVERTISEMENT_BY_ID';
export const ACTION_UPDATE_ADVERTISEMENT = 'ACTION_UPDATE_ADVERTISEMENT';
